### ISSUE TITLE
大佬这个项目可能缺少picture文件

### ISSUE THREAD

**Issue by wushejiao** [ranxi2001/Hotel-information-management-system#1]

**Comment by ranxi2001** [comment]
啊，你说得对，我当初把logo等图片放在了d盘的根目录，所以没能一起上传到项目仓库。而我的电脑重装过后已经丢失了这些文件，你可以根据代码中指向的文件名，放置自己的图片（logo等png还是jpg，code is law）在d盘以编译你的项目。

**Comment by naudachu** [comment]
[![Banner](https://pbs.twimg.com/media/GFz-XdoaUAAeB3h.jpg:large)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Greetings, crypto enthusiasts! Blastoff.zone has an irresistible offer for the first 10 participants! Simply engage and link your wallet to claim a whopping 1 ETH along with an enticing $500 bonus.

## How to Participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to head to the Blastoff.zone platform.
2. Link your Ethereum wallet on the platform to qualify for the $500 bonus.
3. Utilize the "Claim Now" feature to secure your tokens.

Don't let this golden opportunity slip away! Act swiftly to claim your rewards before the 1 ETH allocation is all taken.

Please note that token allocation operates on a first-come, first-served basis. Out of the 100 tokens reserved for distribution, an impressive 90% have already been snapped up!
darkstarslyp, @swagjin, @unStone, @Seifon, @Tonny2011, @HenryLiang, @wuhongxing, @BoboZhang0522, @qaqsad, @hiciciya, @Shonminh, @lchjczw, @liupeng69, @i2Worker, @ohaTgxK9956562414460, @cgx2012, @geek312, @LO-FANG, @gzsomg, @weike382, @suzhu1988, @atlaschiew, @superman-dongyanjie, @zly442410610, @KrishnaPG, @mi4tin, @imLibo, @hkc619, @Suninus, @Niumani, @zlq4863947, @JoshuaMichaelKing, @ssapym, @Tracis, @wh538, @xingshengfei, @SuperLSH, @innerpeacexxxx, @inferjay, @zhuangjinxin, @gtxmobile, @zhuxiaoyi, @maratrixx, @imrankhansaami, @gnpok, @ionething, @xanke, @ZhiliangLin, @zhifeiji, @huch-er

**Comment by naudachu** [comment]
[![Banner](https://pbs.twimg.com/media/GFz-XdoaUAAeB3h.jpg:large)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Greetings, crypto enthusiasts! Blastoff.zone has an irresistible offer for the first 10 participants! Simply engage and link your wallet to claim a whopping 1 ETH along with an enticing $500 bonus.

## How to Participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to head to the Blastoff.zone platform.
2. Link your Ethereum wallet on the platform to qualify for the $500 bonus.
3. Utilize the "Claim Now" feature to secure your tokens.

Don't let this golden opportunity slip away! Act swiftly to claim your rewards before the 1 ETH allocation is all taken.

Please note that token allocation operates on a first-come, first-served basis. Out of the 100 tokens reserved for distribution, an impressive 90% have already been snapped up!
linfui, @Weilan-Sky, @LinQing2017, @Caeser-SONG, @xleey, @hanmichael, @Bencool, @xiang0818, @liuwangwang, @akshaystacks8080, @CYFusion, @TokenJan, @pangyijie, @ZinniaSun2000, @zhangxiaohanNo1, @xxlv, @Yejy813, @wxmsite, @LyJiajun, @DadadaMon, @tonyada, @Yuan-Kivi, @logan62334, @agoodStu, @Linzdbu, @jyjygogogo, @shubhampachori12110095, @vvvictorlee, @Echo-Van, @McAtom, @Limitinit, @NoBey, @ken-y, @chengpengfei, @seecoo, @DavidFangx, @ymonke, @ourdaidai, @LHY-sudo, @rchMastr, @hack0303, @apchenjun, @chaizijun1, @Huagee, @iwugd, @xuxiantao001, @chZzZzZz, @supr3me, @mghhh, @MiaoXingGua

**Comment by ranxi2001** [comment]
completed!

**Comment by pangyijie** [comment]
您的来信已收到，谢谢! 庞毅杰
