### ISSUE TITLE
About pictures

### ISSUE THREAD

**Issue by Zzrsdu** [ranxi2001/Hotel-information-management-system#3]
请问作者pictures文件夹在哪里？

**Comment by ranxi2001** [comment]
本地图片已经丢失，您可按照UI内部的文件命名自行补充
[检索pictures](https://github.com/search?q=repo%3Aranxi2001%2FHotel-information-management-system%20pictures&type=code)
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/5015dea3-d1bc-4a26-b9fa-6fc53b8b146a">

**Comment by Zzrsdu** [comment]
收到，谢谢您的回答

**Comment by Zzrsdu** [comment]
请问作者数据库备份功能可用吗 我这里其他都ok，备份功能界面点开是空白，ui文件也是空白，是要把如图的注释#去掉吗？
![备份](https://github.com/user-attachments/assets/b22ad3e8-d5d9-4559-a035-7bcf66bd122a)

**Comment by ranxi2001** [comment]
一切以实际情况为主，此数据库备份功能应当未完成开发。
基本功能在课程验收完成后，其余部分不再维护，且时间已久，恐无法提供帮助。
